name: run-node-script
on: 
  push:
    branches:
      - master
jobs:
  run-script:
    runs-on: ubuntu-latest
    container: node:18.16
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x src/test.js
      - run: node src/test.js src/test
  