name: run-node-script
on: workflow_dispatch
jobs:
  run-script:
    runs-on: ubuntu-latest
    container: node:18.16
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x scripts/testScript.js
      - run: node scripts/testScript.js
  