name: runTests
on: 
  workflow_call:
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x checkTestOutput.sh
      - run: ./checkTestOutput.sh