name: upload-file
on: workflow_dispatch
jobs:
  check-test:
    uses: ocadotechnology-university/recruitment-support-tool/.github/workflows/runTests.yml@main


  run-script:
    runs-on: ubuntu-latest
    container: node:18.16
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x uploadFile.js
      - run: node uploadFile.js
  