name: upload-file-dispatch
on: workflow_dispatch
env:
  BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}


jobs:
  check-test:
    uses: ocadotechnology-university/recruitment-support-tool/.github/workflows/runTests.yml@main


  run-script:
    runs-on: ubuntu-latest
    container: node:18.16
    steps:
      - uses: actions/checkout@v3
      - run: npm install dotenv --save
      - run: chmod +x uploadFile.js
      - run: node uploadFile.js ./Recruitment
  